version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: trivia-admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-examplepassword}
      POSTGRES_DB: trivia-night
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://trivia-admin:${POSTGRES_PASSWORD:-examplepassword}@db:5432/trivia-night"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
